plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.innei.lody'
version = '0.1.0'

android {
  namespace 'app.innei.lody.kit'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  sourceSets {
    main.assets.srcDir '../licenses'
  }
}

dependencies {
  implementation 'androidx.appcompat:appcompat:1.7.0'
}
